; Code generated by LatteCompiler
section .text
global main
extern printInt, printString, readInt, readString, error, contactString, calloc, malloc
main:
enter 0, 0
mov rax, 3
push rax
mov rdi, [rsp]
mov rsi, 8
call calloc
push rax
mov rax, 3
push rax
mov rdi, [rsp]
mov rsi, 8
call calloc
push rax
mov rdi, 2
mov rsi, 8
call calloc
push rax
mov rax, 0
push rax
mov rax, [rsp + 8]
pop rbx
shl rbx, 3
add rax, rbx
push rax
pop rbx
pop rax
mov [rbx], rax
mov rax, 0
push rax
mov rax, 0
push rax
mov rax, [rsp + 8]
pop rbx
shl rbx, 3
add rax, rbx
push qword [rax]
pop rax
add rax, 0
push rax
pop rbx
pop rax
mov [rbx], rax
mov rdi, 2
mov rsi, 8
call calloc
push rax
mov rax, 2
push rax
mov rdi, [rsp]
mov rsi, 8
call calloc
push rax
mov rax, rsp
add rax, 8
push qword [rax]
pop rax
add rax, 8
push rax
pop rbx
pop rax
mov [rbx], rax
mov rax, 0
push rax
mov rax, rsp
add rax, 8
push qword [rax]
pop rax
add rax, 8
push rax
pop rbx
pop rax
mov [rbx], rax
mov rax, 0
push rax
pop rax
leave
ret
section .data
string_empty db "",0
