; Code generated by LatteCompiler
section .text
global main
extern printInt, printString, readInt, readString, error
main:
enter 0, 0
mov rax, 10
push rax
call fac
sub rsp, 8
push rax
call printInt
sub rsp, 8
push rax
mov rax, 10
push rax
call rfac
sub rsp, 8
push rax
call printInt
sub rsp, 8
push rax
mov rax, 10
push rax
call mfac
sub rsp, 8
push rax
call printInt
sub rsp, 8
push rax
mov rax, 10
push rax
call ifac
sub rsp, 8
push rax
call printInt
sub rsp, 8
push rax
mov rax, qword [string_empty]
push rax
mov rax, 10
push rax
mov rax, 1
push rax
while_10_181_w:
mov rax, [rsp - 16]
push rax
mov rax, 0
push rax
pop rbx
pop rax
cmp rax, rbx
jg cmp_10_188_t
jmp cmp_10_188_f
cmp_10_188_t:
mov rax, 1
jmp cmp_10_188
cmp_10_188_f:
mov rax, 0
cmp_10_188:
push rax
pop rax
cmp rax, 0
je while_10_181
mov rax, [rsp - 8]
push rax
mov rax, [rsp - 24]
push rax
pop rbx
pop rax
mov rdx, 0
imul rax, rbx
push rax
pop rax
mov [rsp - 8], rax
inc qword [rsp - 16]
jmp while_10_181_w
while_10_181:
mov rax, [rsp - 8]
push rax
call printInt
sub rsp, 8
push rax
mov rax, 60
push rax
mov rax, qword [string_1]
push rax
call repStr
sub rsp, 16
push rax
call printString
sub rsp, 8
push rax
mov rax, qword [string_2]
push rax
call printString
sub rsp, 8
push rax
mov rax, qword [string_3]
push rax
call printString
sub rsp, 8
push rax
mov rax, 0
push rax
pop rax
leave
ret
fac:
enter 0, 0
mov rax, 0
push rax
mov rax, 0
push rax
mov rax, 1
push rax
pop rax
mov [rsp - 16], rax
mov rax, [rsp - 24]
push rax
pop rax
mov [rsp - 8], rax
while_28_413_w:
mov rax, [rsp - 8]
push rax
mov rax, 0
push rax
pop rbx
pop rax
cmp rax, rbx
jg cmp_28_420_t
jmp cmp_28_420_f
cmp_28_420_t:
mov rax, 1
jmp cmp_28_420
cmp_28_420_f:
mov rax, 0
cmp_28_420:
push rax
pop rax
cmp rax, 0
je while_28_413
mov rax, [rsp - 16]
push rax
mov rax, [rsp - 16]
push rax
pop rbx
pop rax
mov rdx, 0
imul rax, rbx
push rax
pop rax
mov [rsp - 16], rax
mov rax, [rsp - 8]
push rax
mov rax, 1
push rax
pop rbx
pop rax
sub rax, rbx
push rax
pop rax
mov [rsp - 8], rax
jmp while_28_413_w
while_28_413:
mov rax, [rsp - 16]
push rax
pop rax
leave
ret
rfac:
enter 0, 0
mov rax, [rsp - 8]
push rax
mov rax, 0
push rax
pop rbx
pop rax
cmp rax, rbx
je cmp_36_497_t
jmp cmp_36_497_f
cmp_36_497_t:
mov rax, 1
jmp cmp_36_497
cmp_36_497_f:
mov rax, 0
cmp_36_497:
push rax
pop rax
cmp rax, 0
je condelse_36_493_f
mov rax, 1
push rax
pop rax
leave
ret
jmp condelse_36_493
condelse_36_493_f:
mov rax, [rsp - 8]
push rax
mov rax, [rsp - 16]
push rax
mov rax, 1
push rax
pop rbx
pop rax
sub rax, rbx
push rax
call rfac
sub rsp, 8
push rax
pop rbx
pop rax
mov rdx, 0
imul rax, rbx
push rax
pop rax
leave
ret
condelse_36_493:
mfac:
enter 0, 0
mov rax, [rsp - 8]
push rax
mov rax, 0
push rax
pop rbx
pop rax
cmp rax, rbx
je cmp_43_575_t
jmp cmp_43_575_f
cmp_43_575_t:
mov rax, 1
jmp cmp_43_575
cmp_43_575_f:
mov rax, 0
cmp_43_575:
push rax
pop rax
cmp rax, 0
je condelse_43_571_f
mov rax, 1
push rax
pop rax
leave
ret
jmp condelse_43_571
condelse_43_571_f:
mov rax, [rsp - 8]
push rax
mov rax, [rsp - 16]
push rax
mov rax, 1
push rax
pop rbx
pop rax
sub rax, rbx
push rax
call nfac
sub rsp, 8
push rax
pop rbx
pop rax
mov rdx, 0
imul rax, rbx
push rax
pop rax
leave
ret
condelse_43_571:
nfac:
enter 0, 0
mov rax, [rsp - 8]
push rax
mov rax, 0
push rax
pop rbx
pop rax
cmp rax, rbx
jne cmp_50_653_t
jmp cmp_50_653_f
cmp_50_653_t:
mov rax, 1
jmp cmp_50_653
cmp_50_653_f:
mov rax, 0
cmp_50_653:
push rax
pop rax
cmp rax, 0
je condelse_50_649_f
mov rax, [rsp - 8]
push rax
mov rax, 1
push rax
pop rbx
pop rax
sub rax, rbx
push rax
call mfac
sub rsp, 8
push rax
mov rax, [rsp - 16]
push rax
pop rbx
pop rax
mov rdx, 0
imul rax, rbx
push rax
pop rax
leave
ret
jmp condelse_50_649
condelse_50_649_f:
mov rax, 1
push rax
pop rax
leave
ret
condelse_50_649:
ifac:
enter 0, 0
mov rax, [rsp - 8]
push rax
mov rax, 1
push rax
call ifac2f
sub rsp, 16
push rax
pop rax
leave
ret
ifac2f:
enter 0, 0
mov rax, [rsp - 16]
push rax
mov rax, [rsp - 16]
push rax
pop rbx
pop rax
cmp rax, rbx
je cmp_59_788_t
jmp cmp_59_788_f
cmp_59_788_t:
mov rax, 1
jmp cmp_59_788
cmp_59_788_f:
mov rax, 0
cmp_59_788:
push rax
pop rax
cmp rax, 0
je cond_59_784
mov rax, [rsp - 16]
push rax
pop rax
leave
ret
cond_59_784:
mov rax, [rsp - 16]
push rax
mov rax, [rsp - 16]
push rax
pop rbx
pop rax
cmp rax, rbx
jg cmp_61_828_t
jmp cmp_61_828_f
cmp_61_828_t:
mov rax, 1
jmp cmp_61_828
cmp_61_828_f:
mov rax, 0
cmp_61_828:
push rax
pop rax
cmp rax, 0
je cond_61_824
mov rax, 1
push rax
pop rax
leave
ret
cond_61_824:
mov rax, 0
push rax
mov rax, [rsp - 24]
push rax
mov rax, [rsp - 24]
push rax
pop rbx
pop rax
add rax, rbx
push rax
mov rax, 2
push rax
pop rbx
pop rax
mov rdx, 0
idiv rbx
push rax
pop rax
mov [rsp - 8], rax
mov rax, [rsp - 8]
push rax
mov rax, [rsp - 32]
push rax
call ifac2f
sub rsp, 16
push rax
mov rax, [rsp - 24]
push rax
mov rax, [rsp - 24]
push rax
mov rax, 1
push rax
pop rbx
pop rax
add rax, rbx
push rax
call ifac2f
sub rsp, 16
push rax
pop rbx
pop rax
mov rdx, 0
imul rax, rbx
push rax
pop rax
leave
ret
repStr:
enter 0, 0
mov rax, qword [string_4]
push rax
mov rax, 0
push rax
while_71_1007_w:
mov rax, [rsp - 8]
push rax
mov rax, [rsp - 32]
push rax
pop rbx
pop rax
cmp rax, rbx
jl cmp_71_1013_t
jmp cmp_71_1013_f
cmp_71_1013_t:
mov rax, 1
jmp cmp_71_1013
cmp_71_1013_f:
mov rax, 0
cmp_71_1013:
push rax
pop rax
cmp rax, 0
je while_71_1007
mov rax, [rsp - 16]
push rax
mov rax, [rsp - 40]
push rax
pop rbx
pop rax
push rax
pop rax
mov [rsp - 16], rax
dec qword [rsp - 8]
jmp while_71_1007_w
while_71_1007:
mov rax, [rsp - 16]
push rax
pop rax
leave
ret
section .data
string_2: dd "hello */",0
string_empty: dd "",0
string_1: dd "=",0
string_4: dd "",0
string_3: dd "/* world",0
